name: Run checks

on: [push]

jobs:
  python-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint pyroute2 python-dateutil
        sudo apt update
        sudo apt install -y python3-pyroute2
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py') --fail-under 7 --fail-on E
    - name: Running unit tests
      run: |
        sudo python3 cursed/run_tests.py
